/process/em/verbose 0
/process/had/verbose 0
/vis/verbose 0
/analysis/setFileName test

/run/initialize

#/control/cout/ignoreThreadsExcept 100 # Only the main thread prints things
/run/setCut .01 mm
/gps/particle e-
/gps/ene/type Mono
/gps/ene/mono 1 GeV
/gps/pos/type Plane
/gps/pos/shape Square
/gps/pos/rot1 1 0 0
/gps/pos/rot2 0 1 0
/gps/pos/halfx 0.25 cm
/gps/pos/halfy 0.25 cm
/gps/pos/centre 0 0 -8.5 cm 
/gps/direction 0 .342020 .9396926

/globalField/setValue 0 0 0 tesla
/run/beamOn 2000